"""
Standalone Chatbot API — Generated by GenAI Platform.
Run: uvicorn app:app --host 0.0.0.0 --port 8000
"""
import json
import os
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List

# Load config
with open("config.json") as f:
    CONFIG = json.load(f)

app = FastAPI(title=CONFIG["project_name"] + " Chatbot")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class ChatRequest(BaseModel):
    message: str
    history: List[dict] = []
    session_id: str = "default"


class ChatResponse(BaseModel):
    answer: str
    used_rag: bool = False
    agent_path: list = []
    latency: float = 0.0


@app.get("/health")
def health():
    return {"status": "ok", "project": CONFIG["project_name"]}


@app.post("/chat", response_model=ChatResponse)
async def chat(req: ChatRequest):
    """Process a chat message through the configured pipeline."""
    from core.pipeline import run_pipeline

    result = run_pipeline(
        user_query=req.message,
        chat_history=req.history,
        config=CONFIG,
    )
    return ChatResponse(**result)


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("app:app", host="0.0.0.0", port=8000, reload=True)
